-- Порядок сообщений нельзя строить на created_at: часы в контейнере могут
-- дрейфовать, и ответ получает метку раньше вопроса. Последовательность
-- монотонна независимо от часов.
ALTER TABLE messages ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

UPDATE messages SET seq = ordered.rn
FROM (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn
    FROM messages
) AS ordered
WHERE messages.id = ordered.id;

SELECT setval(pg_get_serial_sequence('messages', 'seq'), COALESCE((SELECT max(seq) FROM messages), 1));

ALTER TABLE messages ALTER COLUMN seq SET NOT NULL;

DROP INDEX messages_chat_id_created_at_idx;
CREATE UNIQUE INDEX messages_chat_id_seq_idx ON messages (chat_id, seq);
